#This container contains your model and any helper scripts specific to your model.
FROM python:3.7
FROM tensorflow/tensorflow:latest-gpu-py3

COPY requirements_gpu.txt /opt/
RUN pip install -r /opt/requirements_gpu.txt

ADD model.py /opt/model.py
RUN chmod +x /opt/model.py

ENTRYPOINT ["python"]
CMD ["/opt/model.py"]
