kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: kfclaim
  namespace: kubeflow
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 18Gi
