apiVersion: v1
data:
  GOOGLE_APPLICATION_CREDENTIALS: /var/secrets/user-gcp-sa.json
  name: painers-gpu-8
  secretMountPath: /var/secrets
  secretName: user-gcp-sa
kind: ConfigMap
metadata:
  name: painters-map-training-c82f674fbt
---
apiVersion: kubeflow.org/v1beta2
kind: TFJob
metadata:
  name: painers-gpu-8
  namespace: kubeflow
spec:
  tfReplicaSpecs:
    Worker:
      replicas: 1
      template:
        spec:
          containers:
          - command:
            - python
            - /opt/model.py
            - --exportdir=gs://painters-mnist-2-1561980951/export/
            - --numclasses=10
            - --dataurl=https://www.dropbox.com/s/hgyjjefanrzqrny/top10_x448.zip?raw=1
            - --epochs=50
            - --batchsize=32
            - --optimizer=adam
            - --lr=0.01
            - --hflip=1
            - --vflip=1
            - --rotation=90
            - --wshift=0.5
            - --hshift=0.5
            - --transferlearning=0
            env:
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: /var/secrets/user-gcp-sa.json
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: /var/secrets/user-gcp-sa.json
            image: gcr.io/painters-mnist-2/kubeflow-train-gpu:1562588163
            name: tensorflow
            resources:
              limits:
                cpu: "4"
                memory: 8Gi
                nvidia.com/gpu: "1"
              requests:
                cpu: "2"
                memory: 4Gi
                nvidia.com/gpu: "1"
            volumeMounts:
            - mountPath: /var/secrets
              name: user-gcp-sa
              readOnly: true
            workingDir: /opt
          restartPolicy: OnFailure
          volumes:
          - name: user-gcp-sa
            secret:
              secretName: user-gcp-sa
