apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
- ../base

configurations:
- params.yaml

# TBD (jinchihe) Need move the image to base file once.
# the issue addressed: kubernetes-sigs/kustomize/issues/1040
# TBD (jinchihe) Need to update the image once
# the issue addressed: kubeflow/testing/issues/373
images:
- name: training-image
  newName: gcr.io/painters-mnist-2/kubeflow-train
  newTag: "1561980951"

vars:
- fieldref:
    fieldPath: data.GOOGLE_APPLICATION_CREDENTIALS
  name: GOOGLE_APPLICATION_CREDENTIALS
  objref:
    apiVersion: v1
    kind: ConfigMap
    name: painters2-training
- fieldref:
    fieldPath: data.secretName
  name: secretName
  objref:
    apiVersion: v1
    kind: ConfigMap
    name: painters2-training
- fieldref:
    fieldPath: data.secretMountPath
  name: secretMountPath
  objref:
    apiVersion: v1
    kind: ConfigMap
    name: painters2-training

      
      
patchesJson6902:
- path: Worker_patch.yaml
  target:
    group: kubeflow.org
    kind: TFJob
    name: $(trainingName)
    version: v1beta1
- path: Ps_patch.yaml
  target:
    group: kubeflow.org
    kind: TFJob
    name: $(trainingName)
    version: v1beta1
- path: Chief_patch.yaml
  target:
    group: kubeflow.org
    kind: TFJob
    name: $(trainingName)
    version: v1beta1
configMapGenerator:
- literals:
  - name=painters2-train-dist
  - trainEpochs=5
  - learningRate=0.01
  - modelDir=gs://painters-mnist-2-1561980951/
  - exportDir=gs://painters-mnist-2-1561980951/export
  - secretName=user-gcp-sa
  - secretMountPath=/var/secrets
  - GOOGLE_APPLICATION_CREDENTIALS=/var/secrets/user-gcp-sa.json
  name: painters2-training
